### ISSUE TITLE
Linker error for Wootric

### ISSUE THREAD

**Issue by taichino** [mParticle/mParticle-iOS-SDK#10]
Hi,

I'm getting following liker error on Xcode 7.2 with the latest mParticle SDK 5.2.0.
    
    ld: framework not found Wootric
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could you make it optional so that we don't have to have Wootric SDK installed?

**Comment by dcirne** [comment]
Hi Taichi,

You can select which kits to install together with the mParticle SDK in your **Podfile**. For example:

```ruby
pod 'mParticle-iOS-SDK/Appboy'
pod 'mParticle-iOS-SDK/BranchMetrics'
pod 'mParticle-iOS-SDK/Localytics'
```

The configuration above would only include the Appboy, BranchMetrics, and Localytics kits.

Furthermore, if you are not including any kit at the moment you can use the following configuration to have only the mParticle SDK added to your project:

```ruby
pod 'mParticle-iOS-SDK/mParticle'
```

Dalmo

**Comment by paulmand** [comment]
Hi Taichi,
Based on what we've discussed with Jesse and Chai - for this app release you should use the only mParticle SDK setup that Dalmo mentioned. Meaning:

pod 'mParticle-iOS-SDK/mParticle'

Paul

**Comment by taichino** [comment]
@dcirne @paulmand Oh, gotcha! Thanks for your quick help! Will specify sub specs we are using :)

**Comment by taichino** [comment]
@paulmand @dcirne umm. something is wrong. we're still getting the linker error above with 

    pod 'mParticle-iOS-SDK/mParticle'

**Comment by paulmand** [comment]
Hi Taichi,
Ahh we noticed something we had pointing to the wrong place. Try updating to SDK 5.2.1. Sorry about that. Things should be good after you try this.

Paul
