### ISSUE TITLE
Error on pod install: "Unable to find targets namaed Pods-mParticle-iOS-SDK_Tests"

### ISSUE THREAD

**Issue by hkellaway** [mParticle/mParticle-iOS-SDK#5]
The README says to do a `pod install` on the Example project to test the library - however, doing so results in an error:

`[!] Unable to find the targets named 'Pods-mParticle-iOS-SDK_Tests' to link with target definition 'mParticle-iOS-SDK_Tests'`

**Comment by dcirne** [comment]
@hkellaway ,

After cloning the repository you will need to change to the respective directory, initialize CocoaPods for the project, configure the Podfile, and only then run `pod install`. Below please find a quick step-by-step:

```shell
$ git clone git@github.com:mParticle/mParticle-iOS-SDK.git
$ cd mParticle-iOS-SDK
$ pod init
```

Open the Podfile in your text editor and configure the target. An example would be:

```ruby
target 'mParticle-iOS-SDK' do
    pod 'mParticle-iOS-SDK', '~> 5'
end
```

Save the Podfile and only then run:

```shell
pod install
```

**Comment by hkellaway** [comment]
@dcirne thanks you. however, that didn't help the fact that pods don't install on the Example project - getting the same error after: '[!] Unable to find the targets named `Pods-mParticle-iOS-SDK_Tests`to link with target definition `mParticle-iOS-SDK_Tests`'

**Comment by dcirne** [comment]
@hkellaway `mParticle-iOS-SDK_Tests` is not a target to run the sample app, it is there just to run unit tests. You can safely delete the section from your Podfile.
